# Generated by Django 4.1.7 on 2023-03-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.CharField(max_length=25500)),
                ("label", models.CharField(max_length=255)),
                ("score", models.FloatField()),
            ],
        ),
    ]
